version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"

  node:
    build: .
    volumes:
      - ./app:/home/node/app/app
    working_dir: /home/node/app
    command: "npm run start"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  redis:  
    image: redis:latest     